---
root: true
parser: "@typescript-eslint/parser"
env:
  node: true
globals:
  BufferEncoding: false
  NodeJS: false
parserOptions:
  ecmaVersion: 2023
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
rules:
  no-undef: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - eslint-config-prettier
